spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: 123456
#  session:
#    store-type: none

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mapper/mybatis-config.xml
#  type-aliases-package: cn.example.domain




